### ISSUE TITLE
シフト管理システムの機能洗い出し

### ISSUE THREAD

**Issue by moriC** [sapodeveloper/shift_manage_system#1]
- [ ] シフト管理システムに必要な機能を洗い出す
- [ ] 洗い出した機能を整理する
- [ ] [wiki](https://github.com/sapodeveloper/shift_manage_system/wiki)に見やすいようにまとめる

**Comment by Mizawa** [comment]
シフト入力システムに必要な機能
- ユーザー機能
  - ユーザ名
  - ログイン名
  - パスワード
  - パスワード変更機能
  - 新規登録機能
- シフトグループ作成機能
  - レギュラー
  - イレギュラーシフト
  - １時間４コマ（１コマ１５分）
- シフト入力機能
  - 午前勤務時間　入力
  - 午後勤務時間　入力
- シフト編集機能
  - ＰＤＦ出力
  - 日付単位編集
  - バックアップ
- シフト出力機能
  - 確定シフト
  - 日別勤務時間表
  - 個別勤務合計時間・日数

シフト入力システムに追加したい機能
・ユーザー機能
　講義入力機能→勤務交代への活用
・シフトグループ作成機能
　イレギュラーシフトのグループ作成機能の充実化→日別・週別
・シフト入力機能
　柔軟な登録機能　最低3日以上の勤務参加で登録の許可→3日未満では申請できないようにする
　勤務時間についてのコメント欄（この時間はなるべく入れて欲しくない・勤務交代可能など）
　シフトをマーカーで塗るように記入（帯を引っ張るような感じ）
・シフト編集機能
　マーカーで塗るようにしてシフトを確定　申請・確定を2段にして表示してほしい
　シフト入力期限の一時的な延長
・シフト出力機能
　個人ごとの勤務時間早見表　スマホ等でも見やすく
・全体
　デザイン　既存エラーの修正　操作性の向上　レスポンシブ対応
