### ISSUE TITLE
DBのマイグレーションファイルを作成する

### ISSUE THREAD

**Issue by moriC** [sapodeveloper/shift_manage_system#10]
#2 で作成したDBのマイグレーションファイルを作成する。

必ず最新のコードの状態で作成すること。
正常にすれば９からの連番で作成できる。

**Comment by nt-2110** [comment]
マイグレーションファイルを作成してみました。
ただ、コミットの形式やブランチなどがよくわからないため、再度作成しないといけないかもしれません。
