### ISSUE TITLE
シフト管理システムのDB設計

### ISSUE THREAD

**Issue by moriC** [sapodeveloper/shift_manage_system#2]
- [ ] 必要な情報を整理する
- [ ] テーブルを作成する
- [ ] 正規化を行い無駄を省く
- [ ] 必要に応じて整理する
- [ ] [共有フォルダ](https://www.dropbox.com/sh/lnka9jqfmojzyvw/DF4q74SKZt)に成果物をupして、みんなが見れるようにする

**Comment by nt-2110** [comment]
共有フォルダにアップロードしたファイルは、「MySQL Workbench」というソフトで開くファイルになっています。
詳細など聞きたい方は、西本までご連絡を。
