### ISSUE TITLE
モックアップを作成する

### ISSUE THREAD

**Issue by moriC** [sapodeveloper/shift_manage_system#3]
- [x] uikitについて調査する
- [x] 上記のCSSフレームワークに従いシフト管理システムのフロントを作成する
  - ログイン画面
  - ログイン後の画面
  - 管理者向け画面
    etc...
- [x] 成果物をみんなと共有できるような場所にupする。リポジトリを作成してもよい。

**Comment by kamera25** [comment]
Uikitについては作成しながらその都度必要な部分をコピペして作ってます。

あと、ログイン画面だけは完成してます。あと2、3個を12日までに作成します。

![screenshot_from_2013-11-08 11 17 41](https://f.cloud.github.com/assets/3379453/1497952/e717a4f4-481c-11e3-8db2-f7e320756185.png)

**Comment by kamera25** [comment]
あと、作っていて思ったのですが、実際に各員のシフトを表示させる表で困ってます。

![screenshot_from_2013-11-08 13 11 04](https://f.cloud.github.com/assets/3379453/1498290/fbe1e8cc-482b-11e3-91c9-ece49ea358e7.png)

↑の画像の表を作成するためのコンポーネントがUIKitにありません。(個人情報保護でぼかしてます)
lessとか素のHTMLのテーブルを使うしかないですかね・・・

**Comment by moriC** [comment]
$BAG$N%F!<%V%k$GA4It:n$C$?$,$J(Bw
$B$"$l$O$a$s$I$+$C$?!#(B($B%^%8$G(B

## 

---

$B9-Eg9)6HBg3X(B
$B>pJs3XIt(B $BCNE*>pJs%7%9%F%`3X2J(B
$B?92<CRM5(B

## E-mail tomohiro.m0219@gmail.com

**Comment by kamera25** [comment]
@moriC 
文字化けしてます。

**Comment by moriC** [comment]
@kamera25 
iPhoneから送ったら化けちゃったか。
素のテーブルを使うしか無いなー。
出来ればヘルパーか何かで自動生成できればいいんだけど…。（チラチラ

**Comment by kamera25** [comment]
どうしましょうね～
自分がそれ系(ヘルパー系)を作ったことないので、どうしようか悩んでます。

**Comment by kamera25** [comment]
ラフ絵
![ccf20131127_00002](https://f.cloud.github.com/assets/3379453/1627943/dd7903ba-56ff-11e3-8a3e-93b884a81e75.jpg)
![ccf20131127_00003](https://f.cloud.github.com/assets/3379453/1627944/e1c5ae3c-56ff-11e3-8a4b-47ab12364f0e.jpg)

**Comment by kamera25** [comment]
kamera25とトヨピーのやるならやらねば TODOリスト
- [x] ログイン画面 (kamera25)
- [x] 個人関連 > 個人トップメニュー (kamera25)
- [x] 個人関連 > シフト確認画面  > シフト列挙
- [ ] 個人関連 > シフト確認画面  > シフト詳細確認 (kamera25/シフト時間表示部分以外完了)
- [x] 個人関連 > シフト入力画面  > 入力可能シフト列挙
- [x] 個人関連 > シフト入力画面  > シフト詳細入力 (レギュラー/イレギュラー共にOK)
- [ ] 個人関連 > 個人設定 ( @Edy1017 /dropbox内の「システム管理者のユーザ情報」を見て作成。)
- [x] 個人関連 > 個人設定 > パスワード変更(Edy1017)
- [x] リーダ関連 > シフト作成 (kamera25/イレギュラーカレンダは @Mizawa が実装予定 )
- [x] リーダ関連 > シフト編成 > シフト列挙
- [x] リーダ関連 > シフト編成 > シフト詳細編成 
- [ ] 内部項目 > ユーザ管理 ( @Edy1017 )
- [ ] 個人関連 > ユーザ管理 > 新規ユーザ追加

**Comment by Edy1017** [comment]
データ編集しました。
確認お願いします。

**Comment by kamera25** [comment]
@Edy1017 
本体に統合しておきました!ありがとう! :+1:

**Comment by kamera25** [comment]
@Edy1017 
Dropbox内の「システム管理者さんのスタッフ情報編集」の画面は作成しないでください。
あとで、 @moriC さんと相談しますので・・・

**Comment by moriC** [comment]
@kamera25 
だいたい新しいモックアップみて思ったのが、
- ボタンをしたときにもっと大胆に色変えた方が見やすいと思う。(例：水色とかオレンジとか選択したことが分かる色に)
- レギュラーシフトのときに10:45までとか、15時までとかってどうするの？(イレギュラーな時間対応)
- レギュラーもイレギュラーも押したらその下に表でも出してリアルタイムに確認できたらよくね？(jsとか使って)

**Comment by kamera25** [comment]
@moriC 
1と3ですが、どちらもjQuery使わないと実装できないですね。
2については、一応説明書きを加えてます。この問題ですが3が出来たら解決できると考えております。

先にリーダ側の編集画面に取り掛かりますので、それが終わり次第諸問題の対処をやります。

**Comment by kamera25** [comment]
@moriC 
一応自分担当分のモック作成一通り終了しました。あとはjQueryとか入れてきます。

**Comment by kamera25** [comment]
@moriC  @Edy1017 
すでにEdy1017がモックアップ作業完了しているので、このイシュー閉じようと思うのですがどうでしょうか？

**Comment by moriC** [comment]
:+1: うむ

**Comment by kamera25** [comment]
@Edy1017 くんによるモックアップ作成が完了したため、このイシューを閉じます。
