### ISSUE TITLE
モックアップの作成

### ISSUE THREAD

**Issue by moriC** [sapodeveloper/shift_manage_system#8]
中奥さんと協力してモックアップの作成をお願いします。

**Comment by kamera25** [comment]
豊嶋くんには今Linuxの勉強をしてもらっています。私と勤務がかぶっていないので、
基本独学で学習中です。

数個コマンドを覚えているとのことです。(cd,cp,mvらへん?)

**Comment by kamera25** [comment]
@Edy1017 くんによるモックアップ作成が完了したため、このイシューを閉じます。
